config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create] do
    get 'downgrade'
    post 'execute_downgrade'
  end


  resources :pages
  
  resources :collaborators

  devise_for :users

  root "welcome#index"

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :page
  belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :collaborators       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

   protected

       def configure_permitted_parameters
           devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
           devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :premium_user) }
       end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_filter :authenticate_user!

def create
  customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
  )

  charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 299,
     description: "BigMoney Membership - #{current_user.email}",
     currency: 'usd'
   )

  @user = current_user
  @user.premium_user = true
  @user.save

  flash[:notice] = "Purchase completed, enjoy!"
  redirect_to root_path

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path

end

def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Pro Membership - #{current_user.email}",
     amount: 299
   }
 end

 def downgrade
   @pages = Page.all
 end

 def execute_downgrade
   @user = current_user
   @user.premium_user = false;
   @user.save
   @allPages = Page.all
   @allPages.each do |page|
     if page.user_id == current_user.id
       page.private = false
       page.save
     end
   end

   flash[:notice] = "Downgraded to Free Account"

   redirect_to edit_user_registration_path
 end


end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create

    @page = Page.find(params[:page_id])
    @collaborator = Collaborator.new(collaborator_params)
    @collaborator.page_id = @page.id
    @allCollabs = Collaborator.all
    #check if collaborator is already on page
    @allCollabs.each do |c|
      if @collaborator.email == c.email
        flash[:alert] ="#{@collaborator.email} is already a collaborator on this page."
        redirect_to edit_page_path(@page.id) and return
      end
    end

    #add user in reference to email
    @users = User.all
    @user_emails = @users.map{|u|u.email}
      if @user_emails.any?{@collaborator.email}
        @users.each do |u|
          if u.email == @collaborator.email
            @page.user_id = u.id
          end
        end
      else
        flash[:alert] ="Please add the email of a current registered user."
        redirect_to edit_page_path(@page.id) and return
      end



    if @collaborator.save
      redirect_to edit_page_path(@page.id), notice: "collaborator was saved successfully."
    else
      flash.now[:alert] = "Error creating collaborator. Please try again."
      render :new
    end
  end

  def new
    @collaborator = Collaborator.new
  end

  def destroy
   @collaborator = Collaborator.find(params[:id])

   if @collaborator.destroy
     flash[:notice] = "#{@collaborator.email} was removed as a collaborator."
     redirect_to pages_path
   else
     flash.now[:alert] = "There was an error removing #{@collaborator.email}."
     render :show
   end
 end

  private

  def collaborator_params
    params.require(:collaborator).permit(:email,:page_id)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index,:show]

  def index
     @pages = policy_scope(Page)
   end

   def show
     @page = Page.find(params[:id])
   end

   def new
     @page = Page.new
   end

   def create
     @page = Page.new(page_params)
     @page.user_id = current_user.id

     if @page.save
       redirect_to @page, notice: "Page was saved successfully."
     else
       flash.now[:alert] = "Error creating page. Please try again."
       render :new
     end
   end

   def edit
     @page = Page.find(params[:id])
     @collaborators = Collaborator.all
   end

   def update
     @page = Page.find(params[:id])

     @page.assign_attributes(page_params)

     if @page.save
        flash[:notice] = "Page was updated."
       redirect_to @page
     else
       flash.now[:alert] = "Error saving page. Please try again."
       render :edit
     end
   end

   def destroy
    @page = Page.find(params[:id])

    if @page.destroy
      flash[:notice] = "\"#{@page.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the page."
      render :show
    end
  end

  private

  def page_params
    params.require(:page).permit(:title, :body, :private)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?

    content_tag :div, capture(&block), class: css_class
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/downgrade.html.erb
<body>


  <h2>Are you sure you would like to downgrade your account?</h2>

  <h4>You are currently not enrolled in a monthly subscription.</h4>

  <h4>The following pages will become public once you downgrade your account:</h4>

  <%@pages.each do |page|%>
    <% if page.user_id == current_user.id%>
      <h3><%= link_to page.title, page %></h3>
    <%end%>
  <%end%>

<div style="margin-top:50px">
  <%= button_to 'Yes, Downgrade', charge_execute_downgrade_path, method: :post %>  <br>
  <h4><%=link_to "Cancel",root_path%></h4>
</div>

</body>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>

  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/_form.html.erb
<%= form_for collaborator do |f| %>
    <%if collaborator.errors.any?%>
      <div class = "alert alert-danger">
        <h4><%= pluralize(collaborator.errors.count, "error")%>.</h4>
        <ul>
          <% collaborator.errors.full_messages.each do |msg|%>
            <li><%=msg%></li>
          <%end%>
        </ul>
      </div>
    <%end%>
    <%= form_group_tag(collaborator.errors[:email]) do %>
     <%= f.label :email %>
     <%= f.text_field :email, class: 'form-control' , placeholder: "Enter Collaborator's Email", :required => true %>

     <%= hidden_field_tag 'page_id', params[:page_id] %>
    <%end%>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>

   </div>


 <% end %>

app/views/collaborators/new.html.erb
<div class="col-md-8">
    <%= render partial: 'form', locals: {collaborator: @collaborator} %>
</div>

<%@page = Page.find(params[:page_id])%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quickscript</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <p>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div style="margin:10px">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for page do |f| %>
    <%if page.errors.any?%>
      <div class = "alert alert-danger">
        <h4><%= pluralize(page.errors.count, "error")%>.</h4>
        <ul>
          <% page.errors.full_messages.each do |msg|%>
            <li><%=msg%></li>
          <%end%>
        </ul>
      </div>
    <%end%>
    <%= form_group_tag(page.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control' , placeholder: "Enter Title", :required => true %>
    <%end%>
    <%= form_group_tag(page.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, class: 'form-control', placeholder: "Enter body" %>
    <%end%>
    <%if current_user.premium_user%>
      <%= form_group_tag(page.errors[:private]) do %>
       <%= f.label :private %>
         <%= f.check_box :private, class: 'checkbox' %>
       <% end %>
    <%end%>
      
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>

<div >
    <%= render partial: 'form', locals: {page: @page} %>



</div>

<%if current_user.premium_user == false%>
  <div>
    <h3>All pages are publicly viewable and editable.</h3>
    <h4>Become a <%=link_to("Premium User",new_charge_path)%> to create private pages.</h4>
  <div>
<%else%>
  <h4>Collaborators</h4>
  <%@collaborators.each do |c|%>
    <%if c.page_id == @page.id%>
      <h5 style="color:grey">
        <%=['😎', '😜','😸','👽','🐼','🐵','🐶','🐯'].sample%>
        <%=c.email%>
        <%= link_to c, method: :delete, data:{confirm: "Remove #{c.email} as a collaborator?"} do %><i class="fa fa-exclamation-triangle"></i> remove<% end %>
      </h5>
    <%else%>
      There are currently no collaborators on this page.
    <%end%>
  <%end%>
  <h4><%=link_to "+ Collaborator to this page",new_collaborator_path(:page_id => @page.id) %></h4>
<%end%>

app/views/pages/index.html.erb
<h1>Pages</h1>

<div class="row">
  <div class="col-md-8">
    <%if current_user == nil || current_user.premium_user != true%>
      <%@pages.each do |page| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <div>
                <%= link_to page.title, page %>
              </div>
            </h4>
              <small>created by <%=User.find(page.user_id).email%></small>
          </div>
        </div>
      <% end %>
    <%elsif current_user.premium_user%>
      <%@pages.each do |page| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <div>
                <%= link_to page.title, page %>
              </div>
            </h4>
              <small>created by <%=User.find(page.user_id).email%></small>
          </div>
        </div>
      <% end %>
    <%end%>
  <div style="margin-top:20px">
    <%= link_to "New Page", new_page_path, class: 'btn btn-success' %>
  </div>

</div>

app/views/pages/new.html.erb
<h1>Pages#new</h1>


<div class="col-md-8">
    <%= render partial: 'form', locals: {page: @page} %>
</div>

<%if current_user.premium_user == false%>
  <div>
    <h3>All pages are publicly viewable and editable.</h3>
    <h4>Become a <%=link_to("Premium User",new_charge_path)%> to create private pages.</h4>
  <div>
<%end%>

app/views/pages/show.html.erb
<h1><%=@page.title%></h1>

<br>
<%markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)%>
<div id='bodyText' style='margin:10px;'></div>
<%@bodyText =  raw markdown.render(@page.body)%>
<%= @bodyText%>



<%= link_to "Edit Page", edit_page_path, class: 'btn btn-primary' %>
<%= link_to "Delete Page", @page, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this Page?' } %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<body style="background:url('http://i.giphy.com/8VtVKx3ehGguY.gif') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;">


  <div class="jumbotron" style="text-align:center; background-color:white; opacity: 0.8; ">
    <h1>⚡️QuickScript⚡️</h1>

    <h3>
      <%= link_to "📝 Pages", pages_path%>
    </h3>
  </div>

</body>